### ISSUE TITLE
[Docs] Is It Possible to Load Text from Site/Page Field?

### ISSUE THREAD

**Issue by luxlogica** [bnomei/kirby3-robots-txt#1]
The docs show how we can configure the robots.txt by using config settings, but is it possible to load the text directly from a field?

Asking because we often setup sites that are going to be 'tweaked' by SEO experts, who sometimes like to change the content on robots.txt - and I'd rather they did this in the Panel, and not have to access the config.php file directly...

**Comment by bnomei** [comment]
sorry. did not notice issue sooner. good idea. all options can be callbacks in v1.0.3.

**Comment by bnomei** [comment]
```php
<?php
return [
    'bnomei.robots-txt.content' => function() {
        return site()->myRobotsTxtContentField()->value();
    },
];
