### ISSUE TITLE
Disable automatic sitemap addition

### ISSUE THREAD

**Issue by bvdputte** [bnomei/kirby3-robots-txt#21]
How can I disable the automatic addition of `sitemap.xml` to robots.txt?

I am also using your feeds plugin, and I assume that's why it gets added? But I do no not use the feeds plugin way to add it, and I'ld like to disable this feature completely from this plugin?

How can I do this? I tried `'bnomei.robots-txt.sitemap' => null` in config.php, but that doesn't do anything.
Looking in the code, I see it checks for presence of known plugins *first* before having options to disable it?

Thx!

**Comment by bnomei** [comment]
valid point. will add asap.

**Comment by bnomei** [comment]
you can disable the sitemap in the feed plugin and the robotstxt plugin will honor that. i built it that way to match the logic of the other plugins.

`bnomei.feed.sitemap.enable => false`
