### ISSUE TITLE
Class 'Bnomei\Robotstxt' not found

### ISSUE THREAD

**Issue by illycz** [bnomei/kirby3-robots-txt#5]
I have installed you plugin on ma local env and everything looks OK.
But on my DEV server I get `Class 'Bnomei\Robotstxt' not found` error.

Can you help me please?

Thanks

**Comment by bnomei** [comment]
i will try. how exactly did you install? downloading the master zip, gitsubmodule or composer? is the error reported by whoops shipping with kirby? can you post a screenshot or the reporting file and line?

**Comment by illycz** [comment]
Sorry I switchet to https://github.com/bvdputte/kirby-fingerprint which is good enought to me.
But I try to reproduce this error and send you more info.

I download your plugin within composer and I get Kirby error. More info later :)

**Comment by illycz** [comment]
Sorry I switchet to https://github.com/omz13/kirby3-wellknown which is good enought to me.
I download your plugin within composer and I get Kirby error.

**Comment by quentin-f451** [comment]
Hi there, 
I've had the exact same error for a few weeks now. 
It seems that the plugin is working perfectly well on another website I started a few months ago on v1.3.1.
But with a more recent setup (v.1.4.6), I have the same error `Class 'Bnomei\Robotstxt' not found`
Do you know where this come from?

**Comment by bnomei** [comment]
i will take a look asap. can you tell me more about your setup? 

- how did you install the plugin? zip, submodule, composer
- which version of kirby?
- if composer have you tried removing vendor folder and composer.lock?

**Comment by quentin-f451** [comment]
I installed it through Composer on v3.3.0. I tried removing vendor and composer.lock, nothing changed. Tried to reinstall through zip, this time it worked.
But, it doesn't work as usual. I use the plugin with `omz13/kirby3-xmlsitemap` and usually, with no setup, I have robots.txt with this:
```
user-agent: *
disallow: /kirby/
disallow: /site/
allow: /media/
sitemap: https://LINK-TO-MY-WEBSITE/sitemap.xml
```
and here, with no setup, I have:
```
user-agent: *
disallow: /
```

Of course, I don't really mind, I can update my config file with what I want. But I was wondering if it may reveal an error.

**Comment by bnomei** [comment]
1) first rule is generated by the plugin on a production server? no debug mode. right? or is this the format you want it to have?

2) if debug is on you will have the second rule. please read this.
https://github.com/bnomei/kirby3-robots-txt#staging-server-debug-mode--disallow-all

**Comment by bnomei** [comment]
will close since inactivity.
